# Generated by Django 5.0.4 on 2024-04-17 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('data', models.DateField(verbose_name='Дата_выхода')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('country', models.CharField(max_length=100, verbose_name='страна')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('street', models.CharField(max_length=100, verbose_name='улица')),
                ('house_number', models.CharField(max_length=10, verbose_name='номер дома')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.IntegerField(choices=[(0, 'Factory'), (1, 'Retailer'), (2, 'Individual')])),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('contacts_email', models.EmailField(max_length=254, verbose_name='email')),
                ('contacts_country', models.CharField(max_length=100, verbose_name='страна')),
                ('contacts_city', models.CharField(max_length=100, verbose_name='город')),
                ('contacts_street', models.CharField(max_length=100, verbose_name='улица')),
                ('contacts_house_number', models.CharField(max_length=10, verbose_name='номер дома')),
                ('debt_to_supplier', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='задолженность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.product', verbose_name='Продукт')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.supplier', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'звено сети',
                'verbose_name_plural': 'звенья сети',
            },
        ),
    ]
